---
title: "EiA Prioritization"
author: "Peter Steward"
date: "1/4/2022"
output: html_document
runtime: shiny
---
  
<style type="text/css">
.main-container {
max-width: 1800px;
margin-left: auto;
margin-right: auto;
}
</style>

```{r setup, include=FALSE}
# Please run getwd() in the console to get the project location and copy into the line below
#root.dir<-"/Users/pstewarda/Library/CloudStorage/OneDrive-CGIAR/Projects/EiA/Climate Prioritization"
#knitr::opts_knit$set(root.dir = root.dir)
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 999)
```

```{r Load packages,echo=F,message=F,warning=F}

if(!require("pacman", character.only = TRUE)){install.packages("pacman",dependencies = T)}

required.packages <- c("arrow",
                       "colourpicker",
                       "data.table",
                       "DT",
                       "dplyr",
                       "ggplot2",
                       "ggpubr",
                       "MetBrewer",
                       "reshape",
                       "shiny",
                    #   "tidyverse",
                       "viridis",
                       "wesanderson")

pacman::p_load(char=required.packages,install = T,character.only = T)

if(require("waffle")==F){
  devtools::install_github("hrbrmstr/waffle")
  require("waffle")
}
 
```

```{r Palette,echo=F}
Viridis<-data.table(Source="viridis",Palette=c("magma","inferno","plasma","viridis","cividis","rocket","mako","turbo"))
Met<-data.table(Source="MetBrewer",Palette=names(MetBrewer::MetPalettes))
Wes<-data.table(Source="wesanderson",Palette=names(wesanderson::wes_palettes))

Palettes<-rbind(Viridis,Met)

PalFun<-function(PalName,N,Names) {
Viridis<-data.table(Source="viridis",Palette=c("magma","inferno","plasma","viridis","cividis","rocket","mako","turbo"))
Met<-data.table(Source="MetBrewer",Palette=names(MetBrewer::MetPalettes))
Palettes<-rbind(Viridis,Met)
    
 if(Palettes[Palette==PalName,Source]=="viridis"){
    PAL<-viridis::viridis(N,option=PalName)
 }

if(Palettes[Palette==PalName,Source]=="MetBrewer"){
     PAL<-MetBrewer::met.brewer(name=PalName, n=N, type="continuous")
}

  if(Palettes[Palette==PalName,Source]=="Wes"){
     PAL<-wesanderson::wes_palette(name=PalName, n=N, type="continuous")
  }
names(PAL)<-Names

return(PAL)
}
```

## EiA Spatial Prioritization  {.tabset .tabset-fade .tabset-pills}

```{r load mapspam, echo =F}
haz_vop_file<-"Data/hazard_vop_admin.parquet"

Data<-data.table(arrow::read_parquet(haz_vop_file))

# Set an mimimum VoP to consider
#MinVoP<-10000 # $I 2015
#Data<-Data[VoP>MinVoP]
```

```{r Create Plot Save Location,echo=F}
PlotDir<-"Plots"
if(!dir.exists(PlotDir)){
  dir.create(PlotDir)
}

```

### WafflePlot
```{r choose region, echo=F}
 cg_regions<- Data[,sort(unique(Region))]
 cg_regions_selected<-cg_regions[cg_regions %in% c("Africa","LAC","SA","SEA")]

  checkboxGroupInput(inputId="Regions", 
                     label="Select regions",
                     choices = cg_regions,
                     selected = cg_regions_selected,
                     inline=T)
```

```{r choose country, echo=F}
# Dynamically filter countries based on selected regions
renderUI({
  req(input$Regions) # Ensure regions are selected

  checkboxGroupInput(inputId="Countries", 
                   label="Select countries",
                   choices =    Data[!is.na(Country) & Country!="" & Region %in% input$Regions,sort(unique(Country))],
                   selected =NULL,
                   inline=T)
})
```

Select the number of crops for each region to show, the top n 

:::: {style="display: flex;"}
::: {}
```{r Choose N Crops, echo=F}
numericInput(inputId="Crop.N1",
             label="No. of crops to show (plot1)",
             value=5,
             min=1,
             max=Data[,list(N=length(unique(Crop))),by=Region][,max(N)],
             step=1,
             width="300px")
```
:::
:::{}
```{r Choose N Crops 2, echo=F}
numericInput(inputId="Crop.N2",
             label="No. of crops to show (plot2)",
             value=20,
             min=1,
             max=50,
             step=1,
             width="300px")
```
:::
:::{}
```{r Choose N Crops 3, echo=F}
numericInput(inputId="Crop.N3",
             label="No. of crops to show (plot3)",
             value=Data[,length(unique(Crop))],
             min=1,
             max=Data[,length(unique(Crop))],
             step=1,
             width="300px")
```
:::
::::

```{r choose crops 2,echo=F}
crop_options<-reactive({
  if(is.null(input$Countries)){
    Data[Region %in% input$Regions & (is.na(Country)|Country==""),sort(unique(Crop))]
  }else{
    Data[Region %in% input$Regions & Country %in% input$Countries,sort(unique(Crop))]
  }
})

renderUI({
  checkboxGroupInput(inputId="crops", 
                     label="Choose Crops",
                     choices = crop_options(),
                     selected = crop_options(),
                     inline=T)
  })

```


```{r set default parameter values,echo=F}
Scaler<-200
NRows<-15
NRows2<-2
FacetRows<-1
TextSize<-20
TextWrap<-"No"
RmNoHaz<-"Yes"
LegPos<-"bottom"
PanelSpace<-0
GridSpace<-0.3
GridCols<-2
GridRows<-3
Palette<-"turbo"
Background<-"white"
GridCol<-"white"
NoHazardCol<-"grey50"
Plot.Height<-0.3
Plot.Width<-1.2
p3_free<-"fixed"
p3_order_val<-"Yes"
p3_unit<-"Billion"
```

:::: {style="display: flex;"}
::: {}
```{r Scaling factor, echo=F}
numericInput(inputId="Scaler",
             label="Max blocks",
             value=Scaler,
             min=0,
             max=2000,
             step=50,
             width="100px")
```
:::
:::{}
```{r Number of Rows, echo=F}
numericInput(inputId="NRows",
             label="Waffle cols-plot1",
             value=NRows,
             min=1,
             max=30,
             step=1,
             width="120px")
```
:::
:::{}
```{r Number of Rows2, echo=F}
numericInput(inputId="NRows2",
             label="Waffle cols-plot2",
             value=NRows2,
             min=1,
             max=30,
             step=1,
             width="120px")
```
:::
:::{}
```{r Number of Facet Rows, echo=F}
numericInput(inputId="FacetRows",
             label="No. facet rows",
             value=FacetRows,
             min=1,
             max=30,
             step=1,
             width="120px")
```
:::
:::{}
```{r Text Size, echo=F}
numericInput(inputId="TextSize",
             label="Text Size",
             value=20,
             min=1,
             max=30,
             step=1,
             width="80px")
```
:::
:::{}
```{r Text Wrap, echo=F}
  selectInput(inputId="TextWrap", 
             label="Wrap labels?",
              choices = c("Yes","No"),
              selected=TextWrap, 
              multiple = F, 
              width="100px")
```
:::
:::{}
```{r RmNoHaz, echo=F}
  selectInput(inputId="RmNoHaz", 
             label="Remove No Hazard?",
              choices = c("Yes","No"),
              selected=RmNoHaz, 
              multiple = F, 
              width="140px")
```
:::
:::{}
```{r LegPos,echo=F}
  selectInput(inputId="LegPos", 
              label="Legend position",
              choices = c("bottom", "right", "top", "left"),
              selected=LegPos, 
              multiple = F, 
              width="120px")
```
:::
:::{}
```{r Facet spacing, echo=F}
numericInput(inputId="PanelSpace",
             label="Facet spacing",
             value=PanelSpace,
             min=1,
             max=30,
             step=1,
             width="110px")
```
:::
:::{}
```{r Grid spacing, echo=F}
numericInput(inputId="GridSpace",
             label="Grid spacing",
             value=GridSpace,
             min=0,
             max=3,
             step=0.01,
             width="110px")
```
:::
:::{}
```{r Grid Cols, echo=F}
numericInput(inputId="GridCols",
             label="Grid columns",
             value=GridCols,
             min=1,
             max=10,
             step=1,
             width="100px")
```
:::
:::{}
```{r Grid Rows, echo=F}

  numericInput(inputId="GridRows",
               label="Grid rows",
               value=GridRows,
               min=1,
               max=10,
               step=1,
               width="100px")

```
:::
:::{}
```{r Plot 3 free, echo=F}

  selectInput(inputId="p3_free",
               label="P3 free y?",
               choices=c("free","fixed"),
               selected=p3_free, 
               multiple = F, 
               width="100px")

```
:::
:::{}
```{r Plot 3 order, echo=F}
  selectInput(inputId="p3_order_val",
               label="P3 order val?",
               choices=c("Yes","No"),
               selected=p3_order_val, 
               multiple = F, 
               width="100px")

```
:::
::::

:::: {style="display: flex;"}
::: {}
```{r Choose Plot,echo=F}
  selectInput(inputId="plot_choice", 
              label="Choose plot",
              choices = c("plot1","plot2","plot3"),
              selected="plot3", 
              multiple = F, 
              width="120px")
```
:::
:::{}
```{r Choose Palette,echo=F}
  selectInput(inputId="Palette", 
              label="Palette",
              choices = Palettes[,sort(Palette)],
              selected=Palette, 
              multiple = F, 
              width="150px")
```
:::
:::{}
```{r Plot background colour picker, echo =F}
  colourInput(inputId="Background",
              label="Background colour",
              value=Background)
```
:::
:::{}
```{r Plot grid colour picker, echo =F}
  colourInput(inputId="GridCol",
              label="Grid colour",
              value=GridCol)
```
:::
:::{}
```{r Plot no hazard colour picker, echo =F}
  colourInput(inputId="NoHazardCol",
              label="No hazard colour",
              value=NoHazardCol)
```
:::
::::

:::: {style="display: flex;"}
::: {}
```{r BigP - Adjust Plot Height, echo=F}
numericInput(inputId="Plot.Height",
             label="Adjust plot height",
             value=Plot.Height,
             min=0.1,
             max=3,
             step=0.05, 
             width="200px")
```
:::
:::{}
```{r Adjust Plot Width , echo=F}
numericInput(inputId="Plot.Width",
             label="Adjust plot width",
             value=Plot.Width,
             min=0.1,
             max=3,
             step=0.1,
             width="200px")
```
:::
:::{}
```{r p3 Choose Unit,echo=F}
  selectInput(inputId="p3_unit", 
              label="P3 VoP Unit",
              choices = c("Thousand","Million","Billion"),
              selected=p3_unit, 
              multiple = F, 
              width="100px")
```
:::
::::

```{r calculate units, echo=F}
dat<-reactive({
    if(is.null(input$Countries)){
    dat<-Data[Region %in% input$Regions & (Country==""|is.na(Country)) & Crop %in% input$crops]
  }else{
    dat<-Data[Country %in% input$Countries & Crop %in% input$crops]
  }
  
  # Add ranks
  rank2<-unique(dat[order(VoP_tot_crop,decreasing = T),.(VoP_tot_crop,Region,Country,Crop)])[,Rank2:=1:.N]
  dat<-merge(dat,rank2,by=c("Region","Crop","Country","VoP_tot_crop"),all.x=T,sort=F)
  
  rank<-unique(dat[order(Region,Country,VoP_tot_crop,decreasing = T),.(Region,Country,VoP_tot_crop,Crop)])[,Rank:=1:.N,by=.(Region,Country)]
  dat<-merge(dat,rank,by=c("Region","Crop","Country","VoP_tot_crop"),all.x=T,sort=F)
  dat
})

square_val<-reactive({
  dat1<-copy(dat())
  ranks<-dat1[,sort(unique(Rank))]
  if(length(ranks)>input$Crop.N1){
  ranks<-ranks[1:input$Crop.N1]
    dat1<-dat1[Rank %in% ranks]
  }
  
  max_vop<-10^(nchar(dat1[,max(VoP)])-2)
  dat1[,VoP:=VoP/max_vop]
  scale_factor<-dat1[,max(VoP,na.rm = T)/input$Scaler]
  round(scale_factor*max_vop/10^6,1)
})

square_val2<-reactive({
  dat2<-copy(dat())
  ranks<-dat2[,sort(unique(Rank2))]
  if(length(ranks)>input$Crop.N2){
  ranks<-ranks[1:input$Crop.N2]
    dat2<-dat2[Rank2 %in% ranks]
  }
  max_vop<-10^(nchar(dat2[,max(VoP)])-2)
  dat2[,VoP:=VoP/max_vop]
  scale_factor<-dat2[,max(VoP,na.rm = T)/input$Scaler]
  round(scale_factor*max_vop/10^6,1)
})

```

Plot 1: Waffle grid unit = `r reactive(square_val())` million IntD 2015. Plot 2: Waffle grid unit = `r reactive(square_val2())` million IntD 2015.

```{r create plot function, echo=F}
#https://rud.is/rpubs/building-waffle-charts.html 

Waffler<-function(data,
                  Crops,
                  Crop.N1,
                  Crop.N2,
                  Crop.N3,
                  Regions,
                  Countries,
                  Scaler,
                  NRows,
                  NRows2,
                  FacetRows,
                  TextSize,
                  HazardPalette,
                  LegPos,
                  PanelSpace,
                  TextWrap,
                  RmNoHaz,
                  Background,
                  NoHazardCol,
                  GridSpace,
                  GridCol,
                  p3_free,
                  p3_order_val,
                  p3_unit){
  
  if(TextWrap=="Yes"){
    data[,Crops:=gsub("oil crops","oil-crops",Crops)]
    data[!grepl(" ",Crop),Crop:=paste0(Crop,"\n")]
    data[,Crop:=gsub(" ","\n",Crop)]
  }

  if(RmNoHaz=="Yes"){
    data<-data[Hazard!="none"]
  }

  # Create combined names
  data[, Combined := paste0(Admin, ":", Crop)]
  data[, Combined := factor(Combined, levels = data[, .(Total = sum(VoP)), by = Combined][order(-Total), Combined])]
  
  # Data for plot 1
  ranks<-data[,sort(unique(Rank))]
  if(length(ranks)>Crop.N1){
  ranks<-ranks[1:Crop.N1]
    data1<-data[Rank %in% ranks]
  } 
  max_vop<-10^(nchar(data1[,max(VoP)])-2)
  data1[,VoP:=VoP/max_vop]
  scale_factor<-data1[,max(VoP,na.rm = T)/Scaler]
  data1[,VoP:=round(VoP/scale_factor,0)]
  MaxY<-data1[,list(Height=ceiling(sum(VoP)/NRows)),by=.(Region,Country,Crop)][,max(Height)]+1
  data1<-data1[VoP>0]
  
  # Data for plot 2
  ranks<-data[,sort(unique(Rank2))]
  if(length(ranks)>Crop.N2){
  ranks<-ranks[1:Crop.N2]
  data2<-data[Rank2 %in% ranks]
  }
  max_vop<-10^(nchar(data2[,max(VoP)])-2)
  data2[,VoP:=VoP/max_vop]
  scale_factor<-data2[,max(VoP,na.rm = T)/Scaler]
  data2[,VoP:=round(VoP/scale_factor,0)]
  data2<-data2[VoP>0]
  
  # Data for plot 3
  data3<-copy(data)
  if(p3_unit=="Million"){
  data3[,VoP:=VoP/10^6]
  }
  if(p3_unit=="Thousand"){
  data3[,VoP:=VoP/10^3]
  }
  if(p3_unit=="Billion"){
  data3[,VoP:=VoP/10^9]
  }

  # Legend Palettes
    hazards1<-data1[,sort(unique(Hazard))]
    hazards2<-data2[,sort(unique(Hazard))]
    hazards3<-data3[,sort(unique(Hazard))]

    HazardPalette1<-PalFun(PalName=HazardPalette,
                      N=length(hazards1),
                      Names=hazards1)
    
    HazardPalette2<-PalFun(PalName=HazardPalette,
                  N=length(hazards2),
                  Names=hazards2)
    
    HazardPalette3<-PalFun(PalName=HazardPalette,
              N=length(hazards2),
              Names=hazards2)
  
   if(RmNoHaz=="No"){
     N<-which(names(HazardPalette1)=="none")
     N1<-which(names(HazardPalette1)!="none")
     HazardPalette1[N]<-NoHazardCol
     HazardPalette1<-HazardPalette1[c(N,N1)]
     
     N<-which(names(HazardPalette2)=="none")
     N1<-which(names(HazardPalette2)!="none")
     HazardPalette2[N]<-NoHazardCol
     HazardPalette2<-HazardPalette2[c(N,N1)]    
     
    N<-which(names(HazardPalette3)=="none")
     N1<-which(names(HazardPalette3)!="none")
     HazardPalette3[N]<-NoHazardCol
     HazardPalette3<-HazardPalette3[c(N,N1)]   
   }
    
    data1[,Hazard:=factor(Hazard,levels = names(HazardPalette1))]
    data2[,Hazard:=factor(Hazard,levels = names(HazardPalette2))]
    data3[,Hazard:=factor(Hazard,levels = rev(names(HazardPalette3)))]

  # Plot 3
  gg_theme <- theme(
  text = element_text(size = TextSize),
  plot.margin = margin(0, 0, 0, 0, unit = "cm"), # Remove plot margin
  panel.spacing = unit(0, "pt"), # No space between panels
  legend.position =  LegPos,
  panel.background = element_rect(fill = Background),
  strip.background = element_blank(),
  strip.text.y.left = element_text(
    angle = 0,                # Horizontal strip labels
    hjust = 1,                # Align strip labels horizontally
    vjust = 0.5,              # Center vertically
    margin = margin(0, 0, 0, 0) # Remove strip margins
  ),
  panel.grid.minor =  element_blank(),
  panel.grid.major.y = element_blank()
  )
  
  crop_order<-data3[,.(VoP=sum(VoP,na.rm=T)),by=Crop][order(VoP,decreasing = T),Crop]

  if(p3_order_val=="Yes"){
    data3$Crop <- factor(data3$Crop, levels = rev(crop_order))
  }else{
    data3$Crop <- factor(data3$Crop, levels = rev(unique(data3$Crop)))
  }
  
  if(Crop.N3<length(crop_order)){
  p3_crops<-crop_order[1:Crop.N3]
  data3<-data3[Crop %in% p3_crops]
  }
  
  g3 <- ggplot(data3, aes(x = Crop, y = VoP, fill = Hazard)) +
  geom_bar(stat = "identity", position =  position_stack(reverse = F), color = GridCol,width=1) +
  scale_fill_manual(values = HazardPalette3, drop = FALSE) +
  facet_grid(. ~ Admin, switch = "y", drop = FALSE,scales = p3_free) +
  theme_minimal() +
  labs(x = NULL, y = paste0("Value of Production (",p3_unit," $I 2015)")) +
  gg_theme+
  scale_y_continuous(expand = c(0.003,0.01))+
  coord_flip()
  plot(g3)
  
  # Plot 2
  gg_theme <- theme(
  text = element_text(size = TextSize),
  plot.margin = margin(0, 0, 0, 0, unit = "cm"), # Remove plot margin
  panel.spacing = unit(0, "lines"), # No space between panels
  axis.ticks = element_blank(),
  axis.line = element_blank(),
  legend.position.inside =  c(0.8, 0.2),
  panel.background = element_rect(fill = Background),
  strip.background = element_blank(),
  strip.text.y.left = element_text(
    angle = 0,                # Horizontal strip labels
    hjust = 1,                # Align strip labels horizontally
    vjust = 0.5,              # Center vertically
    margin = margin(r = 0, l = 0, unit = "pt") # Remove strip margins
  ),
  axis.text = element_blank(),
  axis.title = element_blank(),
  panel.grid = element_blank()
  )
    
  g2 <- ggplot(data2, aes(fill = Hazard, values = VoP)) +
  waffle::geom_waffle(n_rows = NRows2, size = GridSpace, colour = GridCol, flip = FALSE) +
  scale_fill_manual(values = HazardPalette2, drop = FALSE) +
  scale_x_continuous(expand = c(0.005,0))+
  scale_y_continuous(expand = c(0.02,0.02))+
  facet_grid(Combined ~ ., switch = "y") + # Use facet_grid with switched strips
  gg_theme

  # Plot 1
  gg_theme<-theme(text = element_text(size=TextSize),
                  title = element_text(size=TextSize*0.7),
                  panel.spacing = unit(PanelSpace,"lines"),
                  axis.ticks = element_blank(),
                  axis.line = element_blank(),
                  panel.background = element_rect(fill=Background),
                  strip.background = element_blank(),
                  strip.text = element_text(margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "pt")),
                  plot.margin = margin(0, 0, 0, 0, unit = "cm"), 
                  axis.text = element_blank(),
                  axis.title = element_blank(),
                  panel.grid = element_blank())
  
  admin<-data1[,sort(unique(Admin))]
  Plots<-lapply(admin,FUN=function(REG){
    
    Plot.Dat<-data1[Admin==REG]
    
    Plot.Dat[,Crop:=factor(Crop,levels = unique(Plot.Dat[,.(Crop,Rank)])[order(as.numeric(Rank)),Crop])]
  
  g<-ggplot(Plot.Dat,aes(fill = Hazard, values = VoP)) +
    expand_limits(x=c(0,0), y=c(0,0)) +
    coord_equal() +
    labs(fill = NULL, colour = NULL,title = REG) + 
    waffle::geom_waffle(n_rows = NRows, size = GridSpace, colour = GridCol, flip = TRUE)+
    gg_theme+
    scale_fill_manual(values=HazardPalette1,drop=F)+
    facet_wrap(~Crop, nrow = FacetRows, strip.position = "bottom")+
    scale_y_continuous(limits=c(0,MaxY),expand = c(0,0))
  
  g

  })
  
  names(Plots)<-admin

  return(list(Plot1=Plots,Plot2=g2,Plot3=g3))
}

```

```{r create plots,echo=F}
PlotData<-reactive({
  Waffler(data=copy(dat()),
          Crops=input$crops,
          Crop.N1=input$Crop.N1,
          Crop.N2=input$Crop.N2,
          Crop.N3=input$Crop.N3,
          Regions=input$Regions,
          Countries=input$Countries,
          Scaler=input$Scaler,
          NRows=input$NRows,
          NRows2=input$NRows2,
          FacetRows=input$FacetRows,
          TextSize=input$TextSize,
          HazardPalette=input$Palette,
          LegPos=input$LegPos,
          PanelSpace=input$PanelSpace,
          TextWrap=input$TextWrap,
          RmNoHaz=input$RmNoHaz,
          Background=input$Background,
          NoHazardCol=input$NoHazardCol,
          GridSpace=input$GridSpace,
          GridCol=input$GridCol,
          p3_free=input$p3_free,
          p3_order_val=input$p3_order_val,
          p3_unit=input$p3_unit)
})

```

```{r Plot Size Adjust Functions , echo=F}
Plot.Height <- function(){
  x<-  input$Plot.Height*400*length(PlotData()$Plot1)
  if(input$plot_choice %in% c("plot2","plot3")){
  x<- input$Plot.Height*(50+input$Crop.N2*100)
  }
  return(x)
}

Plot.Width <- function(){
  input$Plot.Width*1200
}
```

```{r Plot waffles,echo=F}
renderPlot({
  if(input$plot_choice=="plot1"){

  plot_list<-PlotData()$Plot1
  
  combined_plots<-ggpubr::ggarrange(plotlist=plot_list, 
                    ncol=input$GridCols,
                    nrow=input$GridRows,
                    common.legend = T,
                    legend = input$LegPos)
  
  combined_plots

  }else{
      if(input$plot_choice=="plot2"){
     PlotData()$Plot2
      }else{
      PlotData()$Plot3
      }
  }
  },height= Plot.Height,width=Plot.Width)
```


:::: {style="display: flex;"}
::: {}
```{r  Save Waffle Option, echo=F}
selectInput(inputId="Waffle.Save.Plot", 
            label="Enable Save?",
            choices = c("Yes","No"),
            selected="No",
            width="150px")   
```
:::
:::{}
```{r Waffle Save Width, echo=F}
numericInput(inputId="Waffle.Width",
             label="Plot save width (mm)", 
             value=180,
             min=30,
             max=300,
             step=10,
             width="200px")  
```         
:::
:::{}
```{r Waffle Save Height, echo=F}
numericInput(inputId="Waffle.Height",
             label="Plot save height (mm)", 
             value=180,
             min=30,
             max=300,
             step=10,
             width="220px")  
```   
:::
:::{}
```{r Waffle Scale Height, echo=F}
numericInput(inputId="Waffle.Scale",
             label="Plot scaling", 
             value=1.8,
             min=0.5,
             max=4,
             step=0.1,
             width="200px")  
``` 
:::
:::{}
```{r Waffle - Plot Filename, echo=F}
textInput(inputId="Waffle.Filename",
          label="Enter Waffle filename", 
          value="Waffle")

```
:::
::::
  
```{r Save Waffle, echo=F}
reactive({
  if(input$Waffle.Save.Plot=="Yes"){
    ggsave(filename = paste0(input$Waffle.Filename,".png"),
           plot =   ggpubr::ggarrange(plotlist=PlotData(), 
                    ncol=input$GridCols,
                    nrow=input$GridRows, 
                    common.legend = TRUE, 
                    legend=input$LegPos),
           path = PlotDir,
           width= input$Waffle.Width,
           height = input$Waffle.Height,
           units = "mm",
           scale = input$Waffle.Scale,
           dpi = 600,
           type = "cairo")
  }
})
```


#### Data used the waffle plot:
```{r Show Data,echo=F}
renderDT({
  datatable(Data[,!c("Admin","Label","Rank","Rank2")][,Unit:=paste("I$ 2015")],
            caption="Plot data by crop x region x hazard",
            extensions = 'Buttons',
            filter = "top",
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),c(10,25,50,"All"))))
  
})
```

